import { Product } from "./types";
export const initialProducts: Product[] = [
  {
    id: 1,
    code: "P001",
    name: "Produit 1",
    description: "Description du Produit  1",
    image: "https://picsum.photos/200/200?random=1",
    category: "Category A",
    price: 100,
    quantity: 10,
    internalReference: "REF001",
    shellId: 1,
    inventoryStatus: "INSTOCK",
    rating: 4.5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 2,
    code: "P002",
    name: "Produit 2",
    description: "Description du Produit  2",
    image: "https://picsum.photos/200/200?random=2",
    category: "Category B",
    price: 200,
    quantity: 5,
    internalReference: "REF002",
    shellId: 2,
    inventoryStatus: "LOWSTOCK",
    rating: 4.0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 3,
    code: "P003",
    name: "Produit 3",
    description: "Description du Produit  3",
    image: "https://picsum.photos/200/200?random=3",
    category: "Category A",
    price: 150,
    quantity: 0,
    internalReference: "REF003",
    shellId: 3,
    inventoryStatus: "OUTOFSTOCK",
    rating: 3.5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 4,
    code: "P004",
    name: "Produit 4",
    description: "Description du Produit  4",
    image: "https://picsum.photos/200/200?random=4",
    category: "Category C",
    price: 300,
    quantity: 7,
    internalReference: "REF004",
    shellId: 4,
    inventoryStatus: "INSTOCK",
    rating: 4.8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 5,
    code: "P005",
    name: "Produit 5",
    description: "Description du Produit  5",
    image: "https://picsum.photos/200/200?random=5",
    category: "Category D",
    price: 120,
    quantity: 12,
    internalReference: "REF005",
    shellId: 5,
    inventoryStatus: "INSTOCK",
    rating: 4.3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 6,
    code: "P006",
    name: "Produit 6",
    description: "Description du Produit  6",
    image: "https://picsum.photos/200/200?random=6",
    category: "Category A",
    price: 250,
    quantity: 3,
    internalReference: "REF006",
    shellId: 6,
    inventoryStatus: "LOWSTOCK",
    rating: 4.2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 7,
    code: "P007",
    name: "Produit 7",
    description: "Description du Produit  7",
    image: "https://picsum.photos/200/200?random=7",
    category: "Category B",
    price: 80,
    quantity: 20,
    internalReference: "REF007",
    shellId: 7,
    inventoryStatus: "INSTOCK",
    rating: 4.0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 8,
    code: "P008",
    name: "Produit 8",
    description: "Description du Produit  8",
    image: "https://picsum.photos/200/200?random=8",
    category: "Category C",
    price: 180,
    quantity: 8,
    internalReference: "REF008",
    shellId: 8,
    inventoryStatus: "INSTOCK",
    rating: 4.7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 9,
    code: "P009",
    name: "Produit 9",
    description: "Description du Produit  9",
    image: "https://picsum.photos/200/200?random=9",
    category: "Category D",
    price: 300,
    quantity: 0,
    internalReference: "REF009",
    shellId: 9,
    inventoryStatus: "OUTOFSTOCK",
    rating: 3.9,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 10,
    code: "P010",
    name: "Produit 10",
    description: "Description du Produit  10",
    image: "https://picsum.photos/200/200?random=10",
    category: "Category A",
    price: 60,
    quantity: 25,
    internalReference: "REF010",
    shellId: 10,
    inventoryStatus: "INSTOCK",
    rating: 4.6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 11,
    code: "P011",
    name: "Produit 11",
    description: "Description du Produit  11",
    image: "https://picsum.photos/200/200?random=11",
    category: "Category B",
    price: 90,
    quantity: 18,
    internalReference: "REF011",
    shellId: 11,
    inventoryStatus: "INSTOCK",
    rating: 4.1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 12,
    code: "P012",
    name: "Produit 12",
    description: "Description du Produit  12",
    image: "https://picsum.photos/200/200?random=12",
    category: "Category C",
    price: 400,
    quantity: 2,
    internalReference: "REF012",
    shellId: 12,
    inventoryStatus: "LOWSTOCK",
    rating: 4.9,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 13,
    code: "P013",
    name: "Produit 13",
    description: "Description du Produit  13",
    image: "https://picsum.photos/200/200?random=13",
    category: "Category D",
    price: 50,
    quantity: 35,
    internalReference: "REF013",
    shellId: 13,
    inventoryStatus: "INSTOCK",
    rating: 4.0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 14,
    code: "P014",
    name: "Produit 14",
    description: "Description du Produit  14",
    image: "https://picsum.photos/200/200?random=14",
    category: "Category A",
    price: 75,
    quantity: 15,
    internalReference: "REF014",
    shellId: 14,
    inventoryStatus: "INSTOCK",
    rating: 3.8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 15,
    code: "P015",
    name: "Produit 15",
    description: "Description du Produit  15",
    image: "https://picsum.photos/200/200?random=15",
    category: "Category B",
    price: 270,
    quantity: 4,
    internalReference: "REF015",
    shellId: 15,
    inventoryStatus: "LOWSTOCK",
    rating: 4.4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 16,
    code: "P016",
    name: "Produit 16",
    description: "Description du Produit  16",
    image: "https://picsum.photos/200/200?random=16",
    category: "Category C",
    price: 130,
    quantity: 9,
    internalReference: "REF016",
    shellId: 16,
    inventoryStatus: "INSTOCK",
    rating: 4.2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 17,
    code: "P017",
    name: "Produit 17",
    description: "Description du Produit  17",
    image: "https://picsum.photos/200/200?random=17",
    category: "Category D",
    price: 110,
    quantity: 20,
    internalReference: "REF017",
    shellId: 17,
    inventoryStatus: "INSTOCK",
    rating: 4.0,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];
